version: '3.8'

services: 

  database:
    image: mysql:8.1
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    secrets:
      - root_password
    ports:
      - 3306:3306
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

secrets:
  root_password:
    file: ./server/secrets/database_root_password.txt
