version: '3.8'

services: 

  listok_db:
    image: mysql:latest
    restart: always
    env_file: ./.env
    ports:
      - "3306:3306" # Port mapping correction
    volumes: 
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - db-config:/etc/mysql
      - db-data:/var/lib/mysql
      - ./db/backup/files/:/data_backup/data

volumes:
  db-config:
  db-data:
