-- MySQL Script generated by MySQL Workbench
-- Wed Jan 31 14:56:20 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`users` (
  `user_id` INT NOT NULL,
  `user_email` VARCHAR(45) NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`recipes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`recipes` (
  `recipe_id` INT NOT NULL,
  `user_id` INT NULL,
  `recipe_name` VARCHAR(100) NULL,
  `recipe_desc` MEDIUMTEXT NULL,
  `recipe_method` MEDIUMTEXT NULL,
  `recipe_image` LONGBLOB NULL,
  PRIMARY KEY (`recipe_id`),
  UNIQUE INDEX `recipe_id_UNIQUE` (`recipe_id` ASC) VISIBLE,
  CONSTRAINT `user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`weeks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`weeks` (
  `week_id` INT NOT NULL,
  `user_id` INT NULL,
  `week_start` VARCHAR(45) NULL,
  `recipe_mon` INT NULL,
  `recipe_tue` INT NULL,
  `recipe_wed` INT NULL,
  `recipe_thur` INT NULL,
  `recipe_fri` INT NULL,
  `recipe_sat` INT NULL,
  `recipe_sun` INT NULL,
  PRIMARY KEY (`week_id`),
  INDEX `user_id_idx` (`user_id` ASC) VISIBLE,
  INDEX `recipe_id_idx` (`recipe_mon` ASC, `recipe_tue` ASC, `recipe_wed` ASC, `recipe_thur` ASC, `recipe_fri` ASC, `recipe_sat` ASC, `recipe_sun` ASC) VISIBLE,
  CONSTRAINT `user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `recipe_id`
    FOREIGN KEY (`recipe_mon` , `recipe_tue` , `recipe_wed` , `recipe_thur` , `recipe_fri` , `recipe_sat` , `recipe_sun`)
    REFERENCES `mydb`.`recipes` (`recipe_id` , `recipe_id` , `recipe_id` , `recipe_id` , `recipe_id` , `recipe_id` , `recipe_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
