-- MySQL Script generated by MySQL Workbench
-- Thu Feb  1 19:05:34 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema listok_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema listok_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `listok_db` DEFAULT CHARACTER SET utf8 ;
USE `listok_db` ;

-- -----------------------------------------------------
-- Table `listok_db`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `listok_db`.`users` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `google_id` VARCHAR(100) NULL,
  `user_email` VARCHAR(100) NULL,
  `user_display_name` VARCHAR(100) NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `listok_db`.`recipes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `listok_db`.`recipes` (
  `recipe_id` INT NOT NULL,
  `recipe_name` VARCHAR(100) NULL,
  `recipe_desc` MEDIUMTEXT NULL,
  `recipe_method` MEDIUMTEXT NULL,
  `recipe_image` LONGBLOB NULL,
  `recipe_ingredients` MEDIUMTEXT NULL,
  `users_user_id` INT NOT NULL,
  PRIMARY KEY (`recipe_id`, `users_user_id`),
  UNIQUE INDEX `recipe_id_UNIQUE` (`recipe_id` ASC) VISIBLE,
  INDEX `fk_recipes_users_idx` (`users_user_id` ASC) VISIBLE,
  CONSTRAINT `fk_recipes_users`
    FOREIGN KEY (`users_user_id`)
    REFERENCES `listok_db`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `listok_db`.`weeks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `listok_db`.`weeks` (
  `week_id` INT NOT NULL,
  `week_start` VARCHAR(45) NULL,
  `users_user_id` INT NOT NULL,
  `mon` INT NULL,
  `tue` INT NULL,
  `wed` INT NULL,
  `thur` INT NULL,
  `fri` INT NULL,
  `sat` INT NULL,
  `sun` INT NULL,
  PRIMARY KEY (`week_id`, `users_user_id`),
  INDEX `fk_weeks_users1_idx` (`users_user_id` ASC) VISIBLE,
  CONSTRAINT `fk_weeks_users1`
    FOREIGN KEY (`users_user_id`)
    REFERENCES `listok_db`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `listok_db` ;

-- -----------------------------------------------------
-- Placeholder table for view `listok_db`.`view1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `listok_db`.`view1` (`id` INT);

-- -----------------------------------------------------
-- View `listok_db`.`view1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `listok_db`.`view1`;
USE `listok_db`;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
